/*
 * This file is generated by jOOQ.
*/
package com.demo.sparkjava.api.databasemodel.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Store implements Serializable {

    private static final long serialVersionUID = 147166639;

    private final String uuid;
    private final String name;

    public Store(Store value) {
        this.uuid = value.uuid;
        this.name = value.name;
    }

    public Store(
        String uuid,
        String name
    ) {
        this.uuid = uuid;
        this.name = name;
    }

    public String getUuid() {
        return this.uuid;
    }

    public String getName() {
        return this.name;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Store (");

        sb.append(uuid);
        sb.append(", ").append(name);

        sb.append(")");
        return sb.toString();
    }
}
