/*
 * This file is generated by jOOQ.
*/
package com.demo.sparkjava.api.databasemodel;


import com.demo.sparkjava.api.databasemodel.tables.SchemaVersion;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Store extends SchemaImpl {

    private static final long serialVersionUID = 1892921657;

    /**
     * The reference instance of <code>store</code>
     */
    public static final Store STORE = new Store();

    /**
     * The table <code>store.schema_version</code>.
     */
    public final SchemaVersion SCHEMA_VERSION = com.demo.sparkjava.api.databasemodel.tables.SchemaVersion.SCHEMA_VERSION;

    /**
     * The table <code>store.store</code>.
     */
    public final com.demo.sparkjava.api.databasemodel.tables.Store STORE_ = com.demo.sparkjava.api.databasemodel.tables.Store.STORE_;

    /**
     * No further instances allowed
     */
    private Store() {
        super("store", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            SchemaVersion.SCHEMA_VERSION,
            com.demo.sparkjava.api.databasemodel.tables.Store.STORE_);
    }
}
