  db:
    image: postgres:9.6-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: store
    ports: 
     - 5433:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080